name: Run

on:
  workflow_dispatch:
    # manual run

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: "true"
        token: ${{ secrets.PAT_TOKEN }}
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run
      run: |
        python main.py
    - uses: actions/upload-artifact@v2
      with:
        name: Face2BMI_model
        path: out/*.model
